package main

import (
	"fmt"
	"os"
	"strings"

	"shiro-email/backend/internal/bootstrap"
	"shiro-email/backend/internal/config"
)

func main() {
	if len(os.Args) > 1 {
		switch os.Args[1] {
		case "config-check":
			runConfigCheck()
			return
		case "env-init":
			runEnvInit()
			return
		case "version":
			fmt.Println("shiro-api v2.0.0")
			return
		}
	}
	bootstrap.MustRunHTTPServer()
}

func runConfigCheck() {
	cfg := config.MustLoadConfig()
	errors := 0
	warnings := 0

	check := func(ok bool, label, detail string) {
		if ok {
			fmt.Printf("  \033[32m[OK]\033[0m   %s: %s\n", label, detail)
		} else {
			fmt.Printf("  \033[31m[ERR]\033[0m  %s: %s\n", label, detail)
			errors++
		}
	}
	warn := func(condition bool, label, detail string) {
		if condition {
			fmt.Printf("  \033[33m[WARN]\033[0m %s: %s\n", label, detail)
			warnings++
		}
	}

	fmt.Println("\n  ShiroMail Configuration Check")
	fmt.Println("  " + strings.Repeat("─", 40))

	check(len(cfg.JWTSecret) >= 32, "JWT_SECRET", fmt.Sprintf("%d characters", len(cfg.JWTSecret)))
	warn(cfg.JWTSecret == "dev-secret", "JWT_SECRET", "using default dev secret (insecure)")
	check(cfg.MySQLDSN != "", "MYSQL_DSN", "configured")
	check(cfg.RedisAddr != "", "REDIS_ADDR", cfg.RedisAddr)

	corsJoined := strings.Join(cfg.CORSAllowedOrigins, ",")
	warn(strings.Contains(corsJoined, "localhost"), "CORS_ALLOWED_ORIGINS", "contains localhost (not recommended for production)")
	warn(cfg.AppEnv != "production", "APP_ENV", fmt.Sprintf("set to '%s' (not production)", cfg.AppEnv))
	check(cfg.AppPort != "", "APP_PORT", cfg.AppPort)

	fmt.Println()
	if errors > 0 {
		fmt.Printf("  Result: %d error(s), %d warning(s)\n\n", errors, warnings)
		os.Exit(1)
	} else if warnings > 0 {
		fmt.Printf("  Result: all checks passed with %d warning(s)\n\n", warnings)
	} else {
		fmt.Printf("  Result: all checks passed\n\n")
	}
}

func runEnvInit() {
	template := `# ShiroMail Configuration
# Generated by: shiro-api env-init

# Application
APP_ENV=production
APP_PORT=8080
FRONTEND_PORT=80

# Database
MYSQL_ROOT_PASSWORD=CHANGE_ME_DB_PASSWORD
MYSQL_DATABASE=shiro_email
MYSQL_DSN=root:CHANGE_ME_DB_PASSWORD@tcp(mysql:3306)/shiro_email?parseTime=true

# Redis
REDIS_ADDR=redis:6379
REDIS_PASSWORD=CHANGE_ME_REDIS_PASSWORD

# Security (generate with: openssl rand -base64 48)
JWT_SECRET=CHANGE_ME_JWT_SECRET_MIN_32_CHARS
METRICS_TOKEN=CHANGE_ME_METRICS_TOKEN

# SMTP
SMTP_PORT=25

# Domain
SITE_DOMAIN=mail.example.com
CORS_ALLOWED_ORIGINS=https://mail.example.com

# Docker image
SHIROMAIL_IMAGE=ghcr.io/galiais/shiromail:latest
`
	fmt.Print(template)
}
